### ISSUE TITLE
Notes on Love for Three Oranges

### ISSUE THREAD

**Issue by jkhait** [cul/prokofiev#11]
Item XIII/28 is a list of notes taken by Prokofiev during the rehearsal of Love for Three Oranges. Strictly speaking, this is not a correspondence. Shall we keep it in the folder or move somewhere else?

**Comment by nataliae** [comment]
Good question. We would probably remove it and put it in Misc. But let's keep it where it is for now and check on Tuesday. Is it mentioned in any of the letters?

Could you indicate in the issue what Box & Folder this belongs in?

**Comment by jkhait** [comment]
Box II Folder 1926, October. I don't think Prokofiev planned to send it.

**Comment by nataliae** [comment]
As discussed, indicate the "Type" of document (column S) for now, and we will filter and possibly remove later.
