### ISSUE TITLE
Photos in 1924 Undated folder

### ISSUE THREAD

**Issue by jkhait** [cul/prokofiev#5]
Attached photos are in the 1924 Undated folder. Do you want me to keep them there or would you like to move them to a different place? I couldn't find them neither in the google doc nor in the Goldsmith binder.
![img_0481](https://cloud.githubusercontent.com/assets/14895617/16423672/ff4f5a70-3d2a-11e6-938f-f14045d3ca08.JPG)
![office 20lens 2020160628-122339](https://cloud.githubusercontent.com/assets/14895617/16423750/4688ba76-3d2b-11e6-9700-986c3525817e.jpg)

**Comment by nataliae** [comment]
We do have a separate "photographs" series, and these should be moved there eventually. For now, please move them to the Misc. box (Series II, Sub-series III),  and put them into the 1924 folder (or create one if we don't have one). Do you know who Irina Lukashevich was? Perhaps these are photos related to some other letters from  1924?

**Comment by jkhait** [comment]
It turned out that these photos were sent by Sofia Nikolaevna Nagorskaya with her Nov. 26 1925 letter. Lukashevich was her niece. Shall I put them back to the letter?

**Comment by nataliae** [comment]
Yes, you can add this to the "Notes" column.
