### ISSUE TITLE
Letter date

### ISSUE THREAD

**Issue by jkhait** [cul/prokofiev#6]
![img_0574](https://cloud.githubusercontent.com/assets/14895617/16593472/685cb160-42b3-11e6-88e5-596e83d48609.JPG)
I'm not sure about the date of this letter. Both Google docs and Goldsmith binder place it in July 1925, but for me the date reads more like 1921. What do you think?

**Comment by nataliae** [comment]
It could be either, I think. Any indication in the letter from SP referred to here? I glanced in the spreadsheet, and it looks like the correspondence with A. Jasmin only starts in 1925. Do you know who A. Jasmin was? Could they have met in 1921?
