### ISSUE TITLE
Organization names in Russian -- translate, transliterate, or leave in Cyrillic?

### ISSUE THREAD

**Issue by vesenina26** [cul/prokofiev#7]
Now that we have the Organization columns, the question is how we treat names of Russian organizations that are typed in Cyrillic. Based on the discussion I have just had with Julia, the current practice with French and German names is to keep the original spelling. But we both agree that with Russian names keeping the original spelling may not be the best idea. On the other hand, translating those names into English is pretty difficult (but possible most of the time).
Another way to go is transliteration; organization names are usually lengthy, so they may look rather intimidating in transliteration, but since human names, toponyms, etc. are also transliterated, that may be the best way to go. What do you think?

**Comment by nataliae** [comment]
Yes, you are right: the names of Russian organizations should be transliterated.
Thank you!
